import Foundation

let packageExtensions: Set<String> = [
    "_ulstyle", "_ultheme", "acplugin", "adiumemoticonset", "adiumicon",
    "adiumlibpurpleplugin", "adiumlistlayout", "adiumlisttheme",
    "adiummenubaricons", "adiummessagestyle", "adiumplugin", "adiumscripts",
    "adiumserviceicons", "adiumsoundset", "adiumstatusicons", "adjustments",
    "alfredpreferences", "ani", "apifile", "aplmodel", "appdownload", "appex",
    "appsnapshot", "assembly", "assistant", "avchd", "avm", "band", "bbpackage",
    "bbprojectd", "bentotemplate", "book", "booktemplate", "brushes", "caction",
    "cannedsearch", "card", "cardsmbornes", "cbaccounts", "ccc", "ccl",
    "chocoimg", "cinemagraph", "clr", "cmm", "colloquyemoticons",
    "colloquystyle", "colorpicker", "comic", "cpimage", "cplink", "cptext",
    "cpweb", "cyndata", "cyndicate", "dashsync", "dbwidget", "definition",
    "dext", "dist", "distz", "dlist", "dsclext", "dsym", "dvdmedia",
    "dvtplugin", "dylib", "effects", "emberbackup", "embermdbackup",
    "embersnap", "eomodeld", "epub", "evocamtimelapse", "eyetv", "eyetvloc",
    "eyetvsched", "eyetvtdmp", "familyfile10", "favorite", "fcarch", "fex",
    "framework", "fullbackup", "gbproj", "gchdb", "gdiagramstyle", "glibb",
    "goodnotes", "gputrace", "gradients", "graffle", "gspak", "gstencil",
    "gtemplate", "haslibrary", "highland", "hptask", "hsproj", "huginautocp",
    "hvfproject", "hvpl", "hype", "hypeplugin", "iba", "ibatemplate", "ibooks",
    "ibplugin", "icbu", "ideplugin", "ilmbplugin", "incrementalbackup",
    "instrdst", "internetconnect", "ipa", "ipscannerlaunchextension", "itlb",
    "itmsp-app", "iwdgt", "iwork-tmp", "iwwebpackage", "jpf", "kext",
    "kextcache", "key", "key-tef", "keychain", "keychain-db", "kpf", "kth",
    "latexitplugin", "latexpalette", "layerstyles", "lh3d", "linea",
    "listlayout", "listtheme", "lmnr", "logarchive", "logicx", "loginplugin",
    "lpdf", "lslibrary", "mailstationery", "mbornes", "mdimporter", "mdlabels",
    "mftpkg", "migratedaplibrary", "mindnode", "mindproj", "mkext", "mlproj",
    "moneywell", "monitor", "monitorpanel", "morphx", "mpbinaries", "mproject",
    "mqtz", "mwand", "nbn", "nemolicense", "networkconnect", "neunote", "nib",
    "nmbtemplate", "nnwstyle", "npbackup", "numbers", "numbers-tef", "octest",
    "ofocus", "ofocus-archive", "ofocus-backup", "ofocus-perspective",
    "oo3template", "ooxsl", "oplx", "osax", "p10", "p12", "p7", "p7b", "p7m",
    "p7r", "p7s", "pages", "pages-tef", "pbproj", "pbxproj", "pc3calc",
    "pc3cons", "pc3conv", "pc3func", "pdfd", "pem", "pfx", "pigment", "pkcs12",
    "pkg", "pkpass", "playground", "playgroundbook", "pluginkit", "pocketcasd",
    "ppp", "prefpane", "psdownload", "ptest", "pvback", "pvmdb", "pvoc", "pvt",
    "pvxmdb", "pxm", "pzdoc", "qlgenerator", "qtpxcomposition", "quickpick",
    "qvnote", "qvnotebook", "radarplugin", "raft", "ramd", "rdarplugin", "rgd",
    "ripit", "rtfd", "saver", "scd", "scene", "scn", "scptd", "scsf", "sdsp",
    "seemode", "seetext", "seplugin", "sfrframe", "shapes", "simdevicetype",
    "simruntime", "sites", "sketchpad-flat", "sketchpad-pkg", "skypechatstyle",
    "slidesaver", "soundhoundbookmark", "soundhoundhistory", "soundsmbornes",
    "spdoc", "spreporter", "ssdownload", "storyboardc", "studydeck",
    "suggestionsassets", "task", "testrun", "textbundle", "textexpanderalias",
    "textexpanderbackup", "textexpanderlocal", "textexpandersettings",
    "textstyles", "themembornes", "themepack", "tka", "tkp", "tkv", "tmbundle",
    "tmplugin", "trace", "transport", "tsp", "ulbackup", "ulproject", "ulysses",
    "vellum", "viennastyle", "wand", "wdgt", "webplugin", "webtemplate",
    "webtheme", "wflow", "whink", "wvp", "xcappdata", "xccrashpoint",
    "xcdatamodel", "xcmappingmodel", "xcode", "xcplaygroundpage", "xcplugin",
    "xcprocessorusagepoint", "xcresult", "xcsintegration", "xcsnapshots",
    "xctest", "xctoolchain", "xcyndicate", "xib", "xpc", "zfa",
]
